---
title: "R Assignment 6"
author: "Merrick Howarth"
date: "Nov. 2, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r libraries, include=FALSE}

library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="dbcdeeed2f9e907f31811ee78c1f239a2aa77934")
```


```{r DataRetrieve, include=FALSE, eval = FALSE}


# pums_2019_1yr <- getCensus(
#   name = "acs/acs1/pums",
#   vintage = 2019,
#   region = "public use microdata area:*",
#   regionin = "state:06",
#   vars = c(
#     "SERIALNO",
#     "SPORDER",
#     "PWGTP",
#     "WGTP",
#     "YBL",
#     "BLD",
#     "TEN",
#     "MV",
#     "HINCP",
#     "AGEP"
#   )
# )
# 
# 
#
# saveRDS(pums_2019_1yr, "A6_pums_data.rds")

pums_2019_1yr <- readRDS("A6_pums_data.rds")

```



```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()


sf_pums <-
  pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)





```


```{r leadrisk}

sf_pums_clean <-
  sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)
  ) %>%
  filter(YBL %in% 1:3) %>%
  arrange(AGEP) %>%
  group_by(SERIALNO) %>%
  summarize_all(first) %>%
  mutate (
    leadrisk = (as.numeric(AGEP <= 6) * as.numeric(HINCP <= 90000))
  )


```

```{r logit_model}

# defining BLD, TEN, MV, and PUMA as factors
sf_pums_model <-
  sf_pums_clean %>%
  mutate(
    building_type = BLD %>% 
      factor(
        levels = sf_pums_clean$BLD %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      ),
    
    tenure_type = TEN %>% 
      factor(
        levels = sf_pums_clean$TEN %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      ),
    
    move_type = MV %>% 
      factor(
        levels = sf_pums_clean$MV %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      )
  )


# creating logit model
logit_model <- glm(
  leadrisk ~ building_type + tenure_type + move_type + PUMA,
  family = quasibinomial(),
  data = sf_pums_model
)

summary(logit_model)


```

